---
title: "bootstrapping"
author: "Yu"
date: "November 23, 2020"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(mgcv)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6, 
  out.width = '90%'
)

theme_set(theme_minimal() + theme(legend.position = 'bottom')) 
options(
  ggplot2.continuous.color = 'viridis',
  ggplot2.continuous.fill = 'viridis'
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d


```


```{r}
n_samp = 250

sim_df_const = 
  tibble(
    x = rnorm(n_samp, 1, 1),
    error = rnorm(n_samp, 0, 1),
    y = 2 + 3 * x + error
  )

sim_df_nonconst = sim_df_const %>% 
  mutate(
  error = error * .75 * x,
  y = 2 + 3 * x + error
)
```

plot the datasets

```{r}
sim_df_const %>% 
  ggplot(aes(x =x , y =x))+
  geom_point() +
  geom_smooth(method = 'lm')

sim_df_nonconst %>% 
  ggplot(aes(x =x , y =x))+
  geom_point() +
  geom_smooth(method = 'lm')
```



```{r}
lm(y~x, data = sim_df_const) %>% broom::tidy()
lm(y~x, data = sim_df_nonconst) %>% broom::tidy()
```



## Draw one bootstrap sample

```{r}
boot_sample = function(df){
  
  sample_frac(df, replace = TRUE) %>% 
    arrange(x)
}
```

Check if this works

```{r}
boot_sample(sim_df_nonconst) %>% 
  ggplot(aes(x =x , y =x))+
  geom_point(alpha = .3) +
  geom_smooth(method = 'lm') +
  ylim(-5, 16)
  
```


```{r}
boot_sample(sim_df_nonconst) %>% 
  lm(y~x, data = .) %>% 
  broom::tidy()
  
```


##Many samples and analysis

```{r}
boot_straps = 
  tibble(
    strap_number = 1:1000,
    strap_sample = rerun(1000, boot_sample(sim_df_nonconst))
  )
```


Can I run my analysis on these...?

```{r}
boot_results = 
  boot_straps %>% 
  mutate(
      models= map(.x = strap_sample, ~lm(y~x, data = .x)),
      results = map(models, broom::tidy)
  ) %>% 
  select(strap_number, results) %>% 
  unnest(results)
```

What do I have now?

```{r}
boot_results %>% 
  group_by(term) %>% 
  summarise(
    mean_est = mean(estimate),
    sd_est = sd(estimate)
  )
```


Look at the distributions

```{r}
boot_results %>% 
  filter(term == 'x') %>% 
  ggplot(aes(x = estimate)) +
  geom_density()
```


construct  bootstrap CI

```{r}
boot_results %>% 
  group_by(term) %>% 
  summarise(
    ci_lower = quantile(estimate, 0.025),
    ci_upper = quantile(estimate, 0.975)
  )
```


##Bootstrap using modelr

Can we simplyfy anything ... ?

```{r}
sim_df_nonconst %>% 
  bootstrap(1000, id = 'strap_number') %>% 
  mutate(
      models= map(.x = strap, ~lm(y~x, data = .x)),
      results = map(models, broom::tidy)
  ) %>% 
  select(strap_number, results) %>% 
  unnest(results) %>% 
   group_by(term) %>% 
  summarise(
    mean_est = mean(estimate),
    sd_est = sd(estimate))
```


##Revisit

```{r}
data('nyc_airbnb')

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group
  ) %>% 
  filter(borough != 'Staten Island') %>% 
  select(price,stars, borough, neighbourhood, room_type)

```


```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price)) +
  geom_point()
```


```{r}
airbnb_boot_results = 
nyc_airbnb %>% 
  filter(borough == 'Manhattan') %>% 
  drop_na(stars) %>% 
  bootstrap(1000, id = 'strap_number') %>% 
  mutate(
      models= map(.x = strap, ~lm(price~stars, data = .x)),
      results = map(models, broom::tidy)
  ) %>% 
  select(strap_number, results) %>% 
  unnest(results)

airbnb_boot_results %>% 
   group_by(term) %>% 
  summarise(
    mean_est = mean(estimate),
    sd_est = sd(estimate))
```

Compare this to `lm`

```{r}
nyc_airbnb %>% 
  filter(borough == 'Manhattan') %>% 
  drop_na(stars) %>% 
  lm(price~stars, data = .) %>% 
  broom::tidy()
```

```{r}
airbnb_boot_results %>% 
  filter(term == 'stars') %>% 
  ggplot(aes(x = estimate)) +
  geom_density()
```



